# Tests
DIR_TEST_SOURCES := aliases cscodec-8859 cscodec-ext8 cscodec-utf8 \
	cscodec-utf16 charset filter inputstream parserutils
DIR_TEST_SOURCES := $(DIR_TEST_SOURCES) regression/cscodec-segv \
	regression/filter-segv regression/stream-nomem \
	regression/filter-badenc-segv

include build/makefiles/Makefile.subdir
